// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/membership.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/authaas/api/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MembershipServiceName is the fully-qualified name of the MembershipService service.
	MembershipServiceName = "services.MembershipService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MembershipServiceAddMemberProcedure is the fully-qualified name of the MembershipService's
	// AddMember RPC.
	MembershipServiceAddMemberProcedure = "/services.MembershipService/AddMember"
	// MembershipServiceRemoveMemberProcedure is the fully-qualified name of the MembershipService's
	// RemoveMember RPC.
	MembershipServiceRemoveMemberProcedure = "/services.MembershipService/RemoveMember"
	// MembershipServiceGetDirectMembersProcedure is the fully-qualified name of the MembershipService's
	// GetDirectMembers RPC.
	MembershipServiceGetDirectMembersProcedure = "/services.MembershipService/GetDirectMembers"
	// MembershipServiceGetAllMembersProcedure is the fully-qualified name of the MembershipService's
	// GetAllMembers RPC.
	MembershipServiceGetAllMembersProcedure = "/services.MembershipService/GetAllMembers"
	// MembershipServiceGetDirectGroupsProcedure is the fully-qualified name of the MembershipService's
	// GetDirectGroups RPC.
	MembershipServiceGetDirectGroupsProcedure = "/services.MembershipService/GetDirectGroups"
	// MembershipServiceGetAllGroupsProcedure is the fully-qualified name of the MembershipService's
	// GetAllGroups RPC.
	MembershipServiceGetAllGroupsProcedure = "/services.MembershipService/GetAllGroups"
	// MembershipServiceIsMemberProcedure is the fully-qualified name of the MembershipService's
	// IsMember RPC.
	MembershipServiceIsMemberProcedure = "/services.MembershipService/IsMember"
	// MembershipServiceListGroupsProcedure is the fully-qualified name of the MembershipService's
	// ListGroups RPC.
	MembershipServiceListGroupsProcedure = "/services.MembershipService/ListGroups"
)

// MembershipServiceClient is a client for the services.MembershipService service.
type MembershipServiceClient interface {
	// Add a principal as a member of a group
	AddMember(context.Context, *connect.Request[services.AddMemberRequest]) (*connect.Response[services.AddMemberResponse], error)
	// Remove a principal from a group
	RemoveMember(context.Context, *connect.Request[services.RemoveMemberRequest]) (*connect.Response[services.RemoveMemberResponse], error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(context.Context, *connect.Request[services.GetDirectMembersRequest]) (*connect.Response[services.GetDirectMembersResponse], error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(context.Context, *connect.Request[services.GetAllMembersRequest]) (*connect.Response[services.GetAllMembersResponse], error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(context.Context, *connect.Request[services.GetDirectGroupsRequest]) (*connect.Response[services.GetDirectGroupsResponse], error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(context.Context, *connect.Request[services.GetAllGroupsRequest]) (*connect.Response[services.GetAllGroupsResponse], error)
	// Check if a principal is a member of a group (transitive)
	IsMember(context.Context, *connect.Request[services.IsMemberRequest]) (*connect.Response[services.IsMemberResponse], error)
	// List all groups (principals that have at least one member)
	ListGroups(context.Context, *connect.Request[services.ListGroupsRequest]) (*connect.Response[services.ListGroupsResponse], error)
}

// NewMembershipServiceClient constructs a client for the services.MembershipService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMembershipServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MembershipServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	membershipServiceMethods := services.File_services_membership_proto.Services().ByName("MembershipService").Methods()
	return &membershipServiceClient{
		addMember: connect.NewClient[services.AddMemberRequest, services.AddMemberResponse](
			httpClient,
			baseURL+MembershipServiceAddMemberProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("AddMember")),
			connect.WithClientOptions(opts...),
		),
		removeMember: connect.NewClient[services.RemoveMemberRequest, services.RemoveMemberResponse](
			httpClient,
			baseURL+MembershipServiceRemoveMemberProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("RemoveMember")),
			connect.WithClientOptions(opts...),
		),
		getDirectMembers: connect.NewClient[services.GetDirectMembersRequest, services.GetDirectMembersResponse](
			httpClient,
			baseURL+MembershipServiceGetDirectMembersProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("GetDirectMembers")),
			connect.WithClientOptions(opts...),
		),
		getAllMembers: connect.NewClient[services.GetAllMembersRequest, services.GetAllMembersResponse](
			httpClient,
			baseURL+MembershipServiceGetAllMembersProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("GetAllMembers")),
			connect.WithClientOptions(opts...),
		),
		getDirectGroups: connect.NewClient[services.GetDirectGroupsRequest, services.GetDirectGroupsResponse](
			httpClient,
			baseURL+MembershipServiceGetDirectGroupsProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("GetDirectGroups")),
			connect.WithClientOptions(opts...),
		),
		getAllGroups: connect.NewClient[services.GetAllGroupsRequest, services.GetAllGroupsResponse](
			httpClient,
			baseURL+MembershipServiceGetAllGroupsProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("GetAllGroups")),
			connect.WithClientOptions(opts...),
		),
		isMember: connect.NewClient[services.IsMemberRequest, services.IsMemberResponse](
			httpClient,
			baseURL+MembershipServiceIsMemberProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("IsMember")),
			connect.WithClientOptions(opts...),
		),
		listGroups: connect.NewClient[services.ListGroupsRequest, services.ListGroupsResponse](
			httpClient,
			baseURL+MembershipServiceListGroupsProcedure,
			connect.WithSchema(membershipServiceMethods.ByName("ListGroups")),
			connect.WithClientOptions(opts...),
		),
	}
}

// membershipServiceClient implements MembershipServiceClient.
type membershipServiceClient struct {
	addMember        *connect.Client[services.AddMemberRequest, services.AddMemberResponse]
	removeMember     *connect.Client[services.RemoveMemberRequest, services.RemoveMemberResponse]
	getDirectMembers *connect.Client[services.GetDirectMembersRequest, services.GetDirectMembersResponse]
	getAllMembers    *connect.Client[services.GetAllMembersRequest, services.GetAllMembersResponse]
	getDirectGroups  *connect.Client[services.GetDirectGroupsRequest, services.GetDirectGroupsResponse]
	getAllGroups     *connect.Client[services.GetAllGroupsRequest, services.GetAllGroupsResponse]
	isMember         *connect.Client[services.IsMemberRequest, services.IsMemberResponse]
	listGroups       *connect.Client[services.ListGroupsRequest, services.ListGroupsResponse]
}

// AddMember calls services.MembershipService.AddMember.
func (c *membershipServiceClient) AddMember(ctx context.Context, req *connect.Request[services.AddMemberRequest]) (*connect.Response[services.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls services.MembershipService.RemoveMember.
func (c *membershipServiceClient) RemoveMember(ctx context.Context, req *connect.Request[services.RemoveMemberRequest]) (*connect.Response[services.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// GetDirectMembers calls services.MembershipService.GetDirectMembers.
func (c *membershipServiceClient) GetDirectMembers(ctx context.Context, req *connect.Request[services.GetDirectMembersRequest]) (*connect.Response[services.GetDirectMembersResponse], error) {
	return c.getDirectMembers.CallUnary(ctx, req)
}

// GetAllMembers calls services.MembershipService.GetAllMembers.
func (c *membershipServiceClient) GetAllMembers(ctx context.Context, req *connect.Request[services.GetAllMembersRequest]) (*connect.Response[services.GetAllMembersResponse], error) {
	return c.getAllMembers.CallUnary(ctx, req)
}

// GetDirectGroups calls services.MembershipService.GetDirectGroups.
func (c *membershipServiceClient) GetDirectGroups(ctx context.Context, req *connect.Request[services.GetDirectGroupsRequest]) (*connect.Response[services.GetDirectGroupsResponse], error) {
	return c.getDirectGroups.CallUnary(ctx, req)
}

// GetAllGroups calls services.MembershipService.GetAllGroups.
func (c *membershipServiceClient) GetAllGroups(ctx context.Context, req *connect.Request[services.GetAllGroupsRequest]) (*connect.Response[services.GetAllGroupsResponse], error) {
	return c.getAllGroups.CallUnary(ctx, req)
}

// IsMember calls services.MembershipService.IsMember.
func (c *membershipServiceClient) IsMember(ctx context.Context, req *connect.Request[services.IsMemberRequest]) (*connect.Response[services.IsMemberResponse], error) {
	return c.isMember.CallUnary(ctx, req)
}

// ListGroups calls services.MembershipService.ListGroups.
func (c *membershipServiceClient) ListGroups(ctx context.Context, req *connect.Request[services.ListGroupsRequest]) (*connect.Response[services.ListGroupsResponse], error) {
	return c.listGroups.CallUnary(ctx, req)
}

// MembershipServiceHandler is an implementation of the services.MembershipService service.
type MembershipServiceHandler interface {
	// Add a principal as a member of a group
	AddMember(context.Context, *connect.Request[services.AddMemberRequest]) (*connect.Response[services.AddMemberResponse], error)
	// Remove a principal from a group
	RemoveMember(context.Context, *connect.Request[services.RemoveMemberRequest]) (*connect.Response[services.RemoveMemberResponse], error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(context.Context, *connect.Request[services.GetDirectMembersRequest]) (*connect.Response[services.GetDirectMembersResponse], error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(context.Context, *connect.Request[services.GetAllMembersRequest]) (*connect.Response[services.GetAllMembersResponse], error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(context.Context, *connect.Request[services.GetDirectGroupsRequest]) (*connect.Response[services.GetDirectGroupsResponse], error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(context.Context, *connect.Request[services.GetAllGroupsRequest]) (*connect.Response[services.GetAllGroupsResponse], error)
	// Check if a principal is a member of a group (transitive)
	IsMember(context.Context, *connect.Request[services.IsMemberRequest]) (*connect.Response[services.IsMemberResponse], error)
	// List all groups (principals that have at least one member)
	ListGroups(context.Context, *connect.Request[services.ListGroupsRequest]) (*connect.Response[services.ListGroupsResponse], error)
}

// NewMembershipServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMembershipServiceHandler(svc MembershipServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	membershipServiceMethods := services.File_services_membership_proto.Services().ByName("MembershipService").Methods()
	membershipServiceAddMemberHandler := connect.NewUnaryHandler(
		MembershipServiceAddMemberProcedure,
		svc.AddMember,
		connect.WithSchema(membershipServiceMethods.ByName("AddMember")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceRemoveMemberHandler := connect.NewUnaryHandler(
		MembershipServiceRemoveMemberProcedure,
		svc.RemoveMember,
		connect.WithSchema(membershipServiceMethods.ByName("RemoveMember")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceGetDirectMembersHandler := connect.NewUnaryHandler(
		MembershipServiceGetDirectMembersProcedure,
		svc.GetDirectMembers,
		connect.WithSchema(membershipServiceMethods.ByName("GetDirectMembers")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceGetAllMembersHandler := connect.NewUnaryHandler(
		MembershipServiceGetAllMembersProcedure,
		svc.GetAllMembers,
		connect.WithSchema(membershipServiceMethods.ByName("GetAllMembers")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceGetDirectGroupsHandler := connect.NewUnaryHandler(
		MembershipServiceGetDirectGroupsProcedure,
		svc.GetDirectGroups,
		connect.WithSchema(membershipServiceMethods.ByName("GetDirectGroups")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceGetAllGroupsHandler := connect.NewUnaryHandler(
		MembershipServiceGetAllGroupsProcedure,
		svc.GetAllGroups,
		connect.WithSchema(membershipServiceMethods.ByName("GetAllGroups")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceIsMemberHandler := connect.NewUnaryHandler(
		MembershipServiceIsMemberProcedure,
		svc.IsMember,
		connect.WithSchema(membershipServiceMethods.ByName("IsMember")),
		connect.WithHandlerOptions(opts...),
	)
	membershipServiceListGroupsHandler := connect.NewUnaryHandler(
		MembershipServiceListGroupsProcedure,
		svc.ListGroups,
		connect.WithSchema(membershipServiceMethods.ByName("ListGroups")),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.MembershipService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MembershipServiceAddMemberProcedure:
			membershipServiceAddMemberHandler.ServeHTTP(w, r)
		case MembershipServiceRemoveMemberProcedure:
			membershipServiceRemoveMemberHandler.ServeHTTP(w, r)
		case MembershipServiceGetDirectMembersProcedure:
			membershipServiceGetDirectMembersHandler.ServeHTTP(w, r)
		case MembershipServiceGetAllMembersProcedure:
			membershipServiceGetAllMembersHandler.ServeHTTP(w, r)
		case MembershipServiceGetDirectGroupsProcedure:
			membershipServiceGetDirectGroupsHandler.ServeHTTP(w, r)
		case MembershipServiceGetAllGroupsProcedure:
			membershipServiceGetAllGroupsHandler.ServeHTTP(w, r)
		case MembershipServiceIsMemberProcedure:
			membershipServiceIsMemberHandler.ServeHTTP(w, r)
		case MembershipServiceListGroupsProcedure:
			membershipServiceListGroupsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMembershipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMembershipServiceHandler struct{}

func (UnimplementedMembershipServiceHandler) AddMember(context.Context, *connect.Request[services.AddMemberRequest]) (*connect.Response[services.AddMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.AddMember is not implemented"))
}

func (UnimplementedMembershipServiceHandler) RemoveMember(context.Context, *connect.Request[services.RemoveMemberRequest]) (*connect.Response[services.RemoveMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.RemoveMember is not implemented"))
}

func (UnimplementedMembershipServiceHandler) GetDirectMembers(context.Context, *connect.Request[services.GetDirectMembersRequest]) (*connect.Response[services.GetDirectMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.GetDirectMembers is not implemented"))
}

func (UnimplementedMembershipServiceHandler) GetAllMembers(context.Context, *connect.Request[services.GetAllMembersRequest]) (*connect.Response[services.GetAllMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.GetAllMembers is not implemented"))
}

func (UnimplementedMembershipServiceHandler) GetDirectGroups(context.Context, *connect.Request[services.GetDirectGroupsRequest]) (*connect.Response[services.GetDirectGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.GetDirectGroups is not implemented"))
}

func (UnimplementedMembershipServiceHandler) GetAllGroups(context.Context, *connect.Request[services.GetAllGroupsRequest]) (*connect.Response[services.GetAllGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.GetAllGroups is not implemented"))
}

func (UnimplementedMembershipServiceHandler) IsMember(context.Context, *connect.Request[services.IsMemberRequest]) (*connect.Response[services.IsMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.IsMember is not implemented"))
}

func (UnimplementedMembershipServiceHandler) ListGroups(context.Context, *connect.Request[services.ListGroupsRequest]) (*connect.Response[services.ListGroupsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.MembershipService.ListGroups is not implemented"))
}
