// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/membership.proto

package servicesconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	services "github.com/authaas/api/services"
	sync "sync"
)

const (
	// MembershipServiceName is the fully-qualified name of the MembershipService service.
	MembershipServiceName = "services.MembershipService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MembershipServiceAddMemberProcedure is the procedure name of the MembershipService's AddMember
	// RPC.
	MembershipServiceAddMemberProcedure = "/services.MembershipService/AddMember"
	// MembershipServiceRemoveMemberProcedure is the procedure name of the MembershipService's
	// RemoveMember RPC.
	MembershipServiceRemoveMemberProcedure = "/services.MembershipService/RemoveMember"
	// MembershipServiceGetDirectMembersProcedure is the procedure name of the MembershipService's
	// GetDirectMembers RPC.
	MembershipServiceGetDirectMembersProcedure = "/services.MembershipService/GetDirectMembers"
	// MembershipServiceGetAllMembersProcedure is the procedure name of the MembershipService's
	// GetAllMembers RPC.
	MembershipServiceGetAllMembersProcedure = "/services.MembershipService/GetAllMembers"
	// MembershipServiceGetDirectGroupsProcedure is the procedure name of the MembershipService's
	// GetDirectGroups RPC.
	MembershipServiceGetDirectGroupsProcedure = "/services.MembershipService/GetDirectGroups"
	// MembershipServiceGetAllGroupsProcedure is the procedure name of the MembershipService's
	// GetAllGroups RPC.
	MembershipServiceGetAllGroupsProcedure = "/services.MembershipService/GetAllGroups"
	// MembershipServiceIsMemberProcedure is the procedure name of the MembershipService's IsMember RPC.
	MembershipServiceIsMemberProcedure = "/services.MembershipService/IsMember"
	// MembershipServiceListGroupsProcedure is the procedure name of the MembershipService's ListGroups
	// RPC.
	MembershipServiceListGroupsProcedure = "/services.MembershipService/ListGroups"
)

var (
	membershipServiceAddMemberSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("AddMember"),
			Procedure:  MembershipServiceAddMemberProcedure,
		}
	})
	membershipServiceRemoveMemberSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("RemoveMember"),
			Procedure:  MembershipServiceRemoveMemberProcedure,
		}
	})
	membershipServiceGetDirectMembersSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("GetDirectMembers"),
			Procedure:  MembershipServiceGetDirectMembersProcedure,
		}
	})
	membershipServiceGetAllMembersSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("GetAllMembers"),
			Procedure:  MembershipServiceGetAllMembersProcedure,
		}
	})
	membershipServiceGetDirectGroupsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("GetDirectGroups"),
			Procedure:  MembershipServiceGetDirectGroupsProcedure,
		}
	})
	membershipServiceGetAllGroupsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("GetAllGroups"),
			Procedure:  MembershipServiceGetAllGroupsProcedure,
		}
	})
	membershipServiceIsMemberSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("IsMember"),
			Procedure:  MembershipServiceIsMemberProcedure,
		}
	})
	membershipServiceListGroupsSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_membership_proto.Services().ByName("MembershipService").Methods().ByName("ListGroups"),
			Procedure:  MembershipServiceListGroupsProcedure,
		}
	})
)

// MembershipServiceClient is a client for the services.MembershipService service.
type MembershipServiceClient interface {
	// Add a principal as a member of a group
	AddMember(context.Context, *services.AddMemberRequest) (*services.AddMemberResponse, error)
	// Remove a principal from a group
	RemoveMember(context.Context, *services.RemoveMemberRequest) (*services.RemoveMemberResponse, error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(context.Context, *services.GetDirectMembersRequest) (*services.GetDirectMembersResponse, error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(context.Context, *services.GetAllMembersRequest) (*services.GetAllMembersResponse, error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(context.Context, *services.GetDirectGroupsRequest) (*services.GetDirectGroupsResponse, error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(context.Context, *services.GetAllGroupsRequest) (*services.GetAllGroupsResponse, error)
	// Check if a principal is a member of a group (transitive)
	IsMember(context.Context, *services.IsMemberRequest) (*services.IsMemberResponse, error)
	// List all groups (principals that have at least one member)
	ListGroups(context.Context, *services.ListGroupsRequest) (*services.ListGroupsResponse, error)
}

// NewMembershipServiceClient constructs a client for the services.MembershipService service.
// Multiple service clients may share a single connect.Client.
func NewMembershipServiceClient(client *connect.Client) MembershipServiceClient {
	return &membershipServiceClient{client: client}
}

// MembershipServiceHandler is an implementation of the services.MembershipService service.
type MembershipServiceHandler interface {
	// Add a principal as a member of a group
	AddMember(context.Context, *services.AddMemberRequest) (*services.AddMemberResponse, error)
	// Remove a principal from a group
	RemoveMember(context.Context, *services.RemoveMemberRequest) (*services.RemoveMemberResponse, error)
	// Get direct members of a group (non-transitive)
	GetDirectMembers(context.Context, *services.GetDirectMembersRequest) (*services.GetDirectMembersResponse, error)
	// Get all members of a group (transitive - includes nested groups)
	GetAllMembers(context.Context, *services.GetAllMembersRequest) (*services.GetAllMembersResponse, error)
	// Get direct groups a principal belongs to (non-transitive)
	GetDirectGroups(context.Context, *services.GetDirectGroupsRequest) (*services.GetDirectGroupsResponse, error)
	// Get all groups a principal belongs to (transitive)
	GetAllGroups(context.Context, *services.GetAllGroupsRequest) (*services.GetAllGroupsResponse, error)
	// Check if a principal is a member of a group (transitive)
	IsMember(context.Context, *services.IsMemberRequest) (*services.IsMemberResponse, error)
	// List all groups (principals that have at least one member)
	ListGroups(context.Context, *services.ListGroupsRequest) (*services.ListGroupsResponse, error)
}

// RegisterMembershipServiceHandler registers svc as the services.MembershipService implementation
// on server.
func RegisterMembershipServiceHandler(server *connect.Server, svc MembershipServiceHandler) {
	adapter := membershipServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: membershipServiceAddMemberSpec(), Handler: adapter.addMember},
		connect.Method{Spec: membershipServiceRemoveMemberSpec(), Handler: adapter.removeMember},
		connect.Method{Spec: membershipServiceGetDirectMembersSpec(), Handler: adapter.getDirectMembers},
		connect.Method{Spec: membershipServiceGetAllMembersSpec(), Handler: adapter.getAllMembers},
		connect.Method{Spec: membershipServiceGetDirectGroupsSpec(), Handler: adapter.getDirectGroups},
		connect.Method{Spec: membershipServiceGetAllGroupsSpec(), Handler: adapter.getAllGroups},
		connect.Method{Spec: membershipServiceIsMemberSpec(), Handler: adapter.isMember},
		connect.Method{Spec: membershipServiceListGroupsSpec(), Handler: adapter.listGroups},
	)
}

// UnimplementedMembershipServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMembershipServiceHandler struct{}

func (UnimplementedMembershipServiceHandler) AddMember(context.Context, *services.AddMemberRequest) (*services.AddMemberResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.AddMember is not implemented")
}

func (UnimplementedMembershipServiceHandler) RemoveMember(context.Context, *services.RemoveMemberRequest) (*services.RemoveMemberResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.RemoveMember is not implemented")
}

func (UnimplementedMembershipServiceHandler) GetDirectMembers(context.Context, *services.GetDirectMembersRequest) (*services.GetDirectMembersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.GetDirectMembers is not implemented")
}

func (UnimplementedMembershipServiceHandler) GetAllMembers(context.Context, *services.GetAllMembersRequest) (*services.GetAllMembersResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.GetAllMembers is not implemented")
}

func (UnimplementedMembershipServiceHandler) GetDirectGroups(context.Context, *services.GetDirectGroupsRequest) (*services.GetDirectGroupsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.GetDirectGroups is not implemented")
}

func (UnimplementedMembershipServiceHandler) GetAllGroups(context.Context, *services.GetAllGroupsRequest) (*services.GetAllGroupsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.GetAllGroups is not implemented")
}

func (UnimplementedMembershipServiceHandler) IsMember(context.Context, *services.IsMemberRequest) (*services.IsMemberResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.IsMember is not implemented")
}

func (UnimplementedMembershipServiceHandler) ListGroups(context.Context, *services.ListGroupsRequest) (*services.ListGroupsResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.MembershipService.ListGroups is not implemented")
}

type membershipServiceClient struct {
	client *connect.Client
}

func (c *membershipServiceClient) AddMember(ctx context.Context, req *services.AddMemberRequest) (*services.AddMemberResponse, error) {
	var res services.AddMemberResponse
	if err := c.client.CallUnary(ctx, membershipServiceAddMemberSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) RemoveMember(ctx context.Context, req *services.RemoveMemberRequest) (*services.RemoveMemberResponse, error) {
	var res services.RemoveMemberResponse
	if err := c.client.CallUnary(ctx, membershipServiceRemoveMemberSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) GetDirectMembers(ctx context.Context, req *services.GetDirectMembersRequest) (*services.GetDirectMembersResponse, error) {
	var res services.GetDirectMembersResponse
	if err := c.client.CallUnary(ctx, membershipServiceGetDirectMembersSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) GetAllMembers(ctx context.Context, req *services.GetAllMembersRequest) (*services.GetAllMembersResponse, error) {
	var res services.GetAllMembersResponse
	if err := c.client.CallUnary(ctx, membershipServiceGetAllMembersSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) GetDirectGroups(ctx context.Context, req *services.GetDirectGroupsRequest) (*services.GetDirectGroupsResponse, error) {
	var res services.GetDirectGroupsResponse
	if err := c.client.CallUnary(ctx, membershipServiceGetDirectGroupsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) GetAllGroups(ctx context.Context, req *services.GetAllGroupsRequest) (*services.GetAllGroupsResponse, error) {
	var res services.GetAllGroupsResponse
	if err := c.client.CallUnary(ctx, membershipServiceGetAllGroupsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) IsMember(ctx context.Context, req *services.IsMemberRequest) (*services.IsMemberResponse, error) {
	var res services.IsMemberResponse
	if err := c.client.CallUnary(ctx, membershipServiceIsMemberSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *membershipServiceClient) ListGroups(ctx context.Context, req *services.ListGroupsRequest) (*services.ListGroupsResponse, error) {
	var res services.ListGroupsResponse
	if err := c.client.CallUnary(ctx, membershipServiceListGroupsSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type membershipServiceHandler struct{ svc MembershipServiceHandler }

func (h membershipServiceHandler) addMember(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.AddMemberRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.AddMember(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) removeMember(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.RemoveMemberRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.RemoveMember(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) getDirectMembers(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.GetDirectMembersRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetDirectMembers(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) getAllMembers(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.GetAllMembersRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetAllMembers(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) getDirectGroups(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.GetDirectGroupsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetDirectGroups(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) getAllGroups(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.GetAllGroupsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetAllGroups(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) isMember(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.IsMemberRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.IsMember(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h membershipServiceHandler) listGroups(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.ListGroupsRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ListGroups(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
