// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/principal.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/authaas/api/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PrincipalServiceName is the fully-qualified name of the PrincipalService service.
	PrincipalServiceName = "services.PrincipalService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrincipalServiceDeletePrincipalProcedure is the fully-qualified name of the PrincipalService's
	// DeletePrincipal RPC.
	PrincipalServiceDeletePrincipalProcedure = "/services.PrincipalService/DeletePrincipal"
	// PrincipalServiceGetGrantHashProcedure is the fully-qualified name of the PrincipalService's
	// GetGrantHash RPC.
	PrincipalServiceGetGrantHashProcedure = "/services.PrincipalService/GetGrantHash"
	// PrincipalServiceClearGrantProcedure is the fully-qualified name of the PrincipalService's
	// ClearGrant RPC.
	PrincipalServiceClearGrantProcedure = "/services.PrincipalService/ClearGrant"
)

// PrincipalServiceClient is a client for the services.PrincipalService service.
type PrincipalServiceClient interface {
	// Delete principal
	DeletePrincipal(context.Context, *connect.Request[services.DeletePrincipalRequest]) (*connect.Response[services.DeletePrincipalResponse], error)
	// Retrieve a grant
	GetGrantHash(context.Context, *connect.Request[services.GetGrantHashRequest]) (*connect.Response[services.GetGrantHashResponse], error)
	// Consume a grant
	ClearGrant(context.Context, *connect.Request[services.ClearGrantRequest]) (*connect.Response[services.ClearGrantResponse], error)
}

// NewPrincipalServiceClient constructs a client for the services.PrincipalService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPrincipalServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PrincipalServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	principalServiceMethods := services.File_services_principal_proto.Services().ByName("PrincipalService").Methods()
	return &principalServiceClient{
		deletePrincipal: connect.NewClient[services.DeletePrincipalRequest, services.DeletePrincipalResponse](
			httpClient,
			baseURL+PrincipalServiceDeletePrincipalProcedure,
			connect.WithSchema(principalServiceMethods.ByName("DeletePrincipal")),
			connect.WithClientOptions(opts...),
		),
		getGrantHash: connect.NewClient[services.GetGrantHashRequest, services.GetGrantHashResponse](
			httpClient,
			baseURL+PrincipalServiceGetGrantHashProcedure,
			connect.WithSchema(principalServiceMethods.ByName("GetGrantHash")),
			connect.WithClientOptions(opts...),
		),
		clearGrant: connect.NewClient[services.ClearGrantRequest, services.ClearGrantResponse](
			httpClient,
			baseURL+PrincipalServiceClearGrantProcedure,
			connect.WithSchema(principalServiceMethods.ByName("ClearGrant")),
			connect.WithClientOptions(opts...),
		),
	}
}

// principalServiceClient implements PrincipalServiceClient.
type principalServiceClient struct {
	deletePrincipal *connect.Client[services.DeletePrincipalRequest, services.DeletePrincipalResponse]
	getGrantHash    *connect.Client[services.GetGrantHashRequest, services.GetGrantHashResponse]
	clearGrant      *connect.Client[services.ClearGrantRequest, services.ClearGrantResponse]
}

// DeletePrincipal calls services.PrincipalService.DeletePrincipal.
func (c *principalServiceClient) DeletePrincipal(ctx context.Context, req *connect.Request[services.DeletePrincipalRequest]) (*connect.Response[services.DeletePrincipalResponse], error) {
	return c.deletePrincipal.CallUnary(ctx, req)
}

// GetGrantHash calls services.PrincipalService.GetGrantHash.
func (c *principalServiceClient) GetGrantHash(ctx context.Context, req *connect.Request[services.GetGrantHashRequest]) (*connect.Response[services.GetGrantHashResponse], error) {
	return c.getGrantHash.CallUnary(ctx, req)
}

// ClearGrant calls services.PrincipalService.ClearGrant.
func (c *principalServiceClient) ClearGrant(ctx context.Context, req *connect.Request[services.ClearGrantRequest]) (*connect.Response[services.ClearGrantResponse], error) {
	return c.clearGrant.CallUnary(ctx, req)
}

// PrincipalServiceHandler is an implementation of the services.PrincipalService service.
type PrincipalServiceHandler interface {
	// Delete principal
	DeletePrincipal(context.Context, *connect.Request[services.DeletePrincipalRequest]) (*connect.Response[services.DeletePrincipalResponse], error)
	// Retrieve a grant
	GetGrantHash(context.Context, *connect.Request[services.GetGrantHashRequest]) (*connect.Response[services.GetGrantHashResponse], error)
	// Consume a grant
	ClearGrant(context.Context, *connect.Request[services.ClearGrantRequest]) (*connect.Response[services.ClearGrantResponse], error)
}

// NewPrincipalServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPrincipalServiceHandler(svc PrincipalServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	principalServiceMethods := services.File_services_principal_proto.Services().ByName("PrincipalService").Methods()
	principalServiceDeletePrincipalHandler := connect.NewUnaryHandler(
		PrincipalServiceDeletePrincipalProcedure,
		svc.DeletePrincipal,
		connect.WithSchema(principalServiceMethods.ByName("DeletePrincipal")),
		connect.WithHandlerOptions(opts...),
	)
	principalServiceGetGrantHashHandler := connect.NewUnaryHandler(
		PrincipalServiceGetGrantHashProcedure,
		svc.GetGrantHash,
		connect.WithSchema(principalServiceMethods.ByName("GetGrantHash")),
		connect.WithHandlerOptions(opts...),
	)
	principalServiceClearGrantHandler := connect.NewUnaryHandler(
		PrincipalServiceClearGrantProcedure,
		svc.ClearGrant,
		connect.WithSchema(principalServiceMethods.ByName("ClearGrant")),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.PrincipalService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PrincipalServiceDeletePrincipalProcedure:
			principalServiceDeletePrincipalHandler.ServeHTTP(w, r)
		case PrincipalServiceGetGrantHashProcedure:
			principalServiceGetGrantHashHandler.ServeHTTP(w, r)
		case PrincipalServiceClearGrantProcedure:
			principalServiceClearGrantHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPrincipalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrincipalServiceHandler struct{}

func (UnimplementedPrincipalServiceHandler) DeletePrincipal(context.Context, *connect.Request[services.DeletePrincipalRequest]) (*connect.Response[services.DeletePrincipalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.PrincipalService.DeletePrincipal is not implemented"))
}

func (UnimplementedPrincipalServiceHandler) GetGrantHash(context.Context, *connect.Request[services.GetGrantHashRequest]) (*connect.Response[services.GetGrantHashResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.PrincipalService.GetGrantHash is not implemented"))
}

func (UnimplementedPrincipalServiceHandler) ClearGrant(context.Context, *connect.Request[services.ClearGrantRequest]) (*connect.Response[services.ClearGrantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.PrincipalService.ClearGrant is not implemented"))
}
