// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/principal.proto

package servicesconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	services "github.com/authaas/api/services"
	sync "sync"
)

const (
	// PrincipalServiceName is the fully-qualified name of the PrincipalService service.
	PrincipalServiceName = "services.PrincipalService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PrincipalServiceDeletePrincipalProcedure is the procedure name of the PrincipalService's
	// DeletePrincipal RPC.
	PrincipalServiceDeletePrincipalProcedure = "/services.PrincipalService/DeletePrincipal"
	// PrincipalServiceGetGrantHashProcedure is the procedure name of the PrincipalService's
	// GetGrantHash RPC.
	PrincipalServiceGetGrantHashProcedure = "/services.PrincipalService/GetGrantHash"
	// PrincipalServiceClearGrantProcedure is the procedure name of the PrincipalService's ClearGrant
	// RPC.
	PrincipalServiceClearGrantProcedure = "/services.PrincipalService/ClearGrant"
)

var (
	principalServiceDeletePrincipalSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_principal_proto.Services().ByName("PrincipalService").Methods().ByName("DeletePrincipal"),
			Procedure:  PrincipalServiceDeletePrincipalProcedure,
		}
	})
	principalServiceGetGrantHashSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_principal_proto.Services().ByName("PrincipalService").Methods().ByName("GetGrantHash"),
			Procedure:  PrincipalServiceGetGrantHashProcedure,
		}
	})
	principalServiceClearGrantSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_principal_proto.Services().ByName("PrincipalService").Methods().ByName("ClearGrant"),
			Procedure:  PrincipalServiceClearGrantProcedure,
		}
	})
)

// PrincipalServiceClient is a client for the services.PrincipalService service.
type PrincipalServiceClient interface {
	// Delete principal
	DeletePrincipal(context.Context, *services.DeletePrincipalRequest) (*services.DeletePrincipalResponse, error)
	// Retrieve a grant
	GetGrantHash(context.Context, *services.GetGrantHashRequest) (*services.GetGrantHashResponse, error)
	// Consume a grant
	ClearGrant(context.Context, *services.ClearGrantRequest) (*services.ClearGrantResponse, error)
}

// NewPrincipalServiceClient constructs a client for the services.PrincipalService service. Multiple
// service clients may share a single connect.Client.
func NewPrincipalServiceClient(client *connect.Client) PrincipalServiceClient {
	return &principalServiceClient{client: client}
}

// PrincipalServiceHandler is an implementation of the services.PrincipalService service.
type PrincipalServiceHandler interface {
	// Delete principal
	DeletePrincipal(context.Context, *services.DeletePrincipalRequest) (*services.DeletePrincipalResponse, error)
	// Retrieve a grant
	GetGrantHash(context.Context, *services.GetGrantHashRequest) (*services.GetGrantHashResponse, error)
	// Consume a grant
	ClearGrant(context.Context, *services.ClearGrantRequest) (*services.ClearGrantResponse, error)
}

// RegisterPrincipalServiceHandler registers svc as the services.PrincipalService implementation on
// server.
func RegisterPrincipalServiceHandler(server *connect.Server, svc PrincipalServiceHandler) {
	adapter := principalServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: principalServiceDeletePrincipalSpec(), Handler: adapter.deletePrincipal},
		connect.Method{Spec: principalServiceGetGrantHashSpec(), Handler: adapter.getGrantHash},
		connect.Method{Spec: principalServiceClearGrantSpec(), Handler: adapter.clearGrant},
	)
}

// UnimplementedPrincipalServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPrincipalServiceHandler struct{}

func (UnimplementedPrincipalServiceHandler) DeletePrincipal(context.Context, *services.DeletePrincipalRequest) (*services.DeletePrincipalResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.PrincipalService.DeletePrincipal is not implemented")
}

func (UnimplementedPrincipalServiceHandler) GetGrantHash(context.Context, *services.GetGrantHashRequest) (*services.GetGrantHashResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.PrincipalService.GetGrantHash is not implemented")
}

func (UnimplementedPrincipalServiceHandler) ClearGrant(context.Context, *services.ClearGrantRequest) (*services.ClearGrantResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.PrincipalService.ClearGrant is not implemented")
}

type principalServiceClient struct {
	client *connect.Client
}

func (c *principalServiceClient) DeletePrincipal(ctx context.Context, req *services.DeletePrincipalRequest) (*services.DeletePrincipalResponse, error) {
	var res services.DeletePrincipalResponse
	if err := c.client.CallUnary(ctx, principalServiceDeletePrincipalSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *principalServiceClient) GetGrantHash(ctx context.Context, req *services.GetGrantHashRequest) (*services.GetGrantHashResponse, error) {
	var res services.GetGrantHashResponse
	if err := c.client.CallUnary(ctx, principalServiceGetGrantHashSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *principalServiceClient) ClearGrant(ctx context.Context, req *services.ClearGrantRequest) (*services.ClearGrantResponse, error) {
	var res services.ClearGrantResponse
	if err := c.client.CallUnary(ctx, principalServiceClearGrantSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type principalServiceHandler struct{ svc PrincipalServiceHandler }

func (h principalServiceHandler) deletePrincipal(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.DeletePrincipalRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.DeletePrincipal(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h principalServiceHandler) getGrantHash(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.GetGrantHashRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.GetGrantHash(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h principalServiceHandler) clearGrant(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.ClearGrantRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.ClearGrant(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
