// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/token_verifier.proto

package servicesconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	services "github.com/authaas/api/services"
	sync "sync"
)

const (
	// TokenVerifierServiceName is the fully-qualified name of the TokenVerifierService service.
	TokenVerifierServiceName = "services.TokenVerifierService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokenVerifierServiceDecodeTokenProcedure is the procedure name of the TokenVerifierService's
	// DecodeToken RPC.
	TokenVerifierServiceDecodeTokenProcedure = "/services.TokenVerifierService/DecodeToken"
)

var (
	tokenVerifierServiceDecodeTokenSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_token_verifier_proto.Services().ByName("TokenVerifierService").Methods().ByName("DecodeToken"),
			Procedure:  TokenVerifierServiceDecodeTokenProcedure,
		}
	})
)

// TokenVerifierServiceClient is a client for the services.TokenVerifierService service.
type TokenVerifierServiceClient interface {
	// Decode and validate JWT, returning claims
	DecodeToken(context.Context, *services.DecodeTokenRequest) (*services.DecodeTokenResponse, error)
}

// NewTokenVerifierServiceClient constructs a client for the services.TokenVerifierService service.
// Multiple service clients may share a single connect.Client.
func NewTokenVerifierServiceClient(client *connect.Client) TokenVerifierServiceClient {
	return &tokenVerifierServiceClient{client: client}
}

// TokenVerifierServiceHandler is an implementation of the services.TokenVerifierService service.
type TokenVerifierServiceHandler interface {
	// Decode and validate JWT, returning claims
	DecodeToken(context.Context, *services.DecodeTokenRequest) (*services.DecodeTokenResponse, error)
}

// RegisterTokenVerifierServiceHandler registers svc as the services.TokenVerifierService
// implementation on server.
func RegisterTokenVerifierServiceHandler(server *connect.Server, svc TokenVerifierServiceHandler) {
	adapter := tokenVerifierServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: tokenVerifierServiceDecodeTokenSpec(), Handler: adapter.decodeToken},
	)
}

// UnimplementedTokenVerifierServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokenVerifierServiceHandler struct{}

func (UnimplementedTokenVerifierServiceHandler) DecodeToken(context.Context, *services.DecodeTokenRequest) (*services.DecodeTokenResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.TokenVerifierService.DecodeToken is not implemented")
}

type tokenVerifierServiceClient struct {
	client *connect.Client
}

func (c *tokenVerifierServiceClient) DecodeToken(ctx context.Context, req *services.DecodeTokenRequest) (*services.DecodeTokenResponse, error) {
	var res services.DecodeTokenResponse
	if err := c.client.CallUnary(ctx, tokenVerifierServiceDecodeTokenSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type tokenVerifierServiceHandler struct{ svc TokenVerifierServiceHandler }

func (h tokenVerifierServiceHandler) decodeToken(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.DecodeTokenRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.DecodeToken(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
