// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/token_verifier.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/authaas/api/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TokenVerifierServiceName is the fully-qualified name of the TokenVerifierService service.
	TokenVerifierServiceName = "services.TokenVerifierService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokenVerifierServiceDecodeTokenProcedure is the fully-qualified name of the
	// TokenVerifierService's DecodeToken RPC.
	TokenVerifierServiceDecodeTokenProcedure = "/services.TokenVerifierService/DecodeToken"
)

// TokenVerifierServiceClient is a client for the services.TokenVerifierService service.
type TokenVerifierServiceClient interface {
	// Decode and validate JWT, returning claims
	DecodeToken(context.Context, *connect.Request[services.DecodeTokenRequest]) (*connect.Response[services.DecodeTokenResponse], error)
}

// NewTokenVerifierServiceClient constructs a client for the services.TokenVerifierService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTokenVerifierServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TokenVerifierServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tokenVerifierServiceMethods := services.File_services_token_verifier_proto.Services().ByName("TokenVerifierService").Methods()
	return &tokenVerifierServiceClient{
		decodeToken: connect.NewClient[services.DecodeTokenRequest, services.DecodeTokenResponse](
			httpClient,
			baseURL+TokenVerifierServiceDecodeTokenProcedure,
			connect.WithSchema(tokenVerifierServiceMethods.ByName("DecodeToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tokenVerifierServiceClient implements TokenVerifierServiceClient.
type tokenVerifierServiceClient struct {
	decodeToken *connect.Client[services.DecodeTokenRequest, services.DecodeTokenResponse]
}

// DecodeToken calls services.TokenVerifierService.DecodeToken.
func (c *tokenVerifierServiceClient) DecodeToken(ctx context.Context, req *connect.Request[services.DecodeTokenRequest]) (*connect.Response[services.DecodeTokenResponse], error) {
	return c.decodeToken.CallUnary(ctx, req)
}

// TokenVerifierServiceHandler is an implementation of the services.TokenVerifierService service.
type TokenVerifierServiceHandler interface {
	// Decode and validate JWT, returning claims
	DecodeToken(context.Context, *connect.Request[services.DecodeTokenRequest]) (*connect.Response[services.DecodeTokenResponse], error)
}

// NewTokenVerifierServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTokenVerifierServiceHandler(svc TokenVerifierServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tokenVerifierServiceMethods := services.File_services_token_verifier_proto.Services().ByName("TokenVerifierService").Methods()
	tokenVerifierServiceDecodeTokenHandler := connect.NewUnaryHandler(
		TokenVerifierServiceDecodeTokenProcedure,
		svc.DecodeToken,
		connect.WithSchema(tokenVerifierServiceMethods.ByName("DecodeToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.TokenVerifierService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TokenVerifierServiceDecodeTokenProcedure:
			tokenVerifierServiceDecodeTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTokenVerifierServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokenVerifierServiceHandler struct{}

func (UnimplementedTokenVerifierServiceHandler) DecodeToken(context.Context, *connect.Request[services.DecodeTokenRequest]) (*connect.Response[services.DecodeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.TokenVerifierService.DecodeToken is not implemented"))
}
