// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/token_issuer.proto

package servicesconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	services "github.com/authaas/api/services"
	sync "sync"
)

const (
	// TokenIssuerServiceName is the fully-qualified name of the TokenIssuerService service.
	TokenIssuerServiceName = "services.TokenIssuerService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokenIssuerServiceIssueTokenProcedure is the procedure name of the TokenIssuerService's
	// IssueToken RPC.
	TokenIssuerServiceIssueTokenProcedure = "/services.TokenIssuerService/IssueToken"
)

var (
	tokenIssuerServiceIssueTokenSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_token_issuer_proto.Services().ByName("TokenIssuerService").Methods().ByName("IssueToken"),
			Procedure:  TokenIssuerServiceIssueTokenProcedure,
		}
	})
)

// TokenIssuerServiceClient is a client for the services.TokenIssuerService service.
type TokenIssuerServiceClient interface {
	// Issue a signed JWT
	IssueToken(context.Context, *services.IssueTokenRequest) (*services.IssueTokenResponse, error)
}

// NewTokenIssuerServiceClient constructs a client for the services.TokenIssuerService service.
// Multiple service clients may share a single connect.Client.
func NewTokenIssuerServiceClient(client *connect.Client) TokenIssuerServiceClient {
	return &tokenIssuerServiceClient{client: client}
}

// TokenIssuerServiceHandler is an implementation of the services.TokenIssuerService service.
type TokenIssuerServiceHandler interface {
	// Issue a signed JWT
	IssueToken(context.Context, *services.IssueTokenRequest) (*services.IssueTokenResponse, error)
}

// RegisterTokenIssuerServiceHandler registers svc as the services.TokenIssuerService implementation
// on server.
func RegisterTokenIssuerServiceHandler(server *connect.Server, svc TokenIssuerServiceHandler) {
	adapter := tokenIssuerServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: tokenIssuerServiceIssueTokenSpec(), Handler: adapter.issueToken},
	)
}

// UnimplementedTokenIssuerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokenIssuerServiceHandler struct{}

func (UnimplementedTokenIssuerServiceHandler) IssueToken(context.Context, *services.IssueTokenRequest) (*services.IssueTokenResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.TokenIssuerService.IssueToken is not implemented")
}

type tokenIssuerServiceClient struct {
	client *connect.Client
}

func (c *tokenIssuerServiceClient) IssueToken(ctx context.Context, req *services.IssueTokenRequest) (*services.IssueTokenResponse, error) {
	var res services.IssueTokenResponse
	if err := c.client.CallUnary(ctx, tokenIssuerServiceIssueTokenSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type tokenIssuerServiceHandler struct{ svc TokenIssuerServiceHandler }

func (h tokenIssuerServiceHandler) issueToken(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req services.IssueTokenRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.IssueToken(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
