// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/token_issuer.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/authaas/api/services"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TokenIssuerServiceName is the fully-qualified name of the TokenIssuerService service.
	TokenIssuerServiceName = "services.TokenIssuerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TokenIssuerServiceIssueTokenProcedure is the fully-qualified name of the TokenIssuerService's
	// IssueToken RPC.
	TokenIssuerServiceIssueTokenProcedure = "/services.TokenIssuerService/IssueToken"
)

// TokenIssuerServiceClient is a client for the services.TokenIssuerService service.
type TokenIssuerServiceClient interface {
	// Issue a signed JWT
	IssueToken(context.Context, *connect.Request[services.IssueTokenRequest]) (*connect.Response[services.IssueTokenResponse], error)
}

// NewTokenIssuerServiceClient constructs a client for the services.TokenIssuerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTokenIssuerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TokenIssuerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tokenIssuerServiceMethods := services.File_services_token_issuer_proto.Services().ByName("TokenIssuerService").Methods()
	return &tokenIssuerServiceClient{
		issueToken: connect.NewClient[services.IssueTokenRequest, services.IssueTokenResponse](
			httpClient,
			baseURL+TokenIssuerServiceIssueTokenProcedure,
			connect.WithSchema(tokenIssuerServiceMethods.ByName("IssueToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tokenIssuerServiceClient implements TokenIssuerServiceClient.
type tokenIssuerServiceClient struct {
	issueToken *connect.Client[services.IssueTokenRequest, services.IssueTokenResponse]
}

// IssueToken calls services.TokenIssuerService.IssueToken.
func (c *tokenIssuerServiceClient) IssueToken(ctx context.Context, req *connect.Request[services.IssueTokenRequest]) (*connect.Response[services.IssueTokenResponse], error) {
	return c.issueToken.CallUnary(ctx, req)
}

// TokenIssuerServiceHandler is an implementation of the services.TokenIssuerService service.
type TokenIssuerServiceHandler interface {
	// Issue a signed JWT
	IssueToken(context.Context, *connect.Request[services.IssueTokenRequest]) (*connect.Response[services.IssueTokenResponse], error)
}

// NewTokenIssuerServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTokenIssuerServiceHandler(svc TokenIssuerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tokenIssuerServiceMethods := services.File_services_token_issuer_proto.Services().ByName("TokenIssuerService").Methods()
	tokenIssuerServiceIssueTokenHandler := connect.NewUnaryHandler(
		TokenIssuerServiceIssueTokenProcedure,
		svc.IssueToken,
		connect.WithSchema(tokenIssuerServiceMethods.ByName("IssueToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.TokenIssuerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TokenIssuerServiceIssueTokenProcedure:
			tokenIssuerServiceIssueTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTokenIssuerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTokenIssuerServiceHandler struct{}

func (UnimplementedTokenIssuerServiceHandler) IssueToken(context.Context, *connect.Request[services.IssueTokenRequest]) (*connect.Response[services.IssueTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.TokenIssuerService.IssueToken is not implemented"))
}
