// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/webauthn.proto

package servicesconnect

import (
	connect "connectrpc.com/connect/v2"
	context "context"
	services "github.com/authaas/api/services"
	webauthn "github.com/authaas/api/webauthn"
	sync "sync"
)

const (
	// WebAuthnServiceName is the fully-qualified name of the WebAuthnService service.
	WebAuthnServiceName = "services.WebAuthnService"
)

// These constants are the procedure names of the RPCs defined in this package. They're exposed at
// runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WebAuthnServiceBeginRegisterProcedure is the procedure name of the WebAuthnService's
	// BeginRegister RPC.
	WebAuthnServiceBeginRegisterProcedure = "/services.WebAuthnService/BeginRegister"
	// WebAuthnServiceFinishRegisterProcedure is the procedure name of the WebAuthnService's
	// FinishRegister RPC.
	WebAuthnServiceFinishRegisterProcedure = "/services.WebAuthnService/FinishRegister"
	// WebAuthnServiceBeginLoginProcedure is the procedure name of the WebAuthnService's BeginLogin RPC.
	WebAuthnServiceBeginLoginProcedure = "/services.WebAuthnService/BeginLogin"
	// WebAuthnServiceFinishLoginProcedure is the procedure name of the WebAuthnService's FinishLogin
	// RPC.
	WebAuthnServiceFinishLoginProcedure = "/services.WebAuthnService/FinishLogin"
)

var (
	webAuthnServiceBeginRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods().ByName("BeginRegister"),
			Procedure:  WebAuthnServiceBeginRegisterProcedure,
		}
	})
	webAuthnServiceFinishRegisterSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods().ByName("FinishRegister"),
			Procedure:  WebAuthnServiceFinishRegisterProcedure,
		}
	})
	webAuthnServiceBeginLoginSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods().ByName("BeginLogin"),
			Procedure:  WebAuthnServiceBeginLoginProcedure,
		}
	})
	webAuthnServiceFinishLoginSpec = sync.OnceValue(func() connect.Spec {
		return connect.Spec{
			StreamType: connect.StreamTypeUnary,
			Schema:     services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods().ByName("FinishLogin"),
			Procedure:  WebAuthnServiceFinishLoginProcedure,
		}
	})
)

// WebAuthnServiceClient is a client for the services.WebAuthnService service.
type WebAuthnServiceClient interface {
	// Begin the webauthn registration ceremony
	BeginRegister(context.Context, *webauthn.BeginRegisterRequest) (*webauthn.BeginRegisterResponse, error)
	// Finish the webauthn registration ceremony
	FinishRegister(context.Context, *webauthn.FinishRegisterRequest) (*webauthn.FinishRegisterResponse, error)
	// Begin the webauthn login ceremony
	BeginLogin(context.Context, *webauthn.BeginLoginRequest) (*webauthn.BeginLoginResponse, error)
	// Finish the webauthn login ceremony
	FinishLogin(context.Context, *webauthn.FinishLoginRequest) (*webauthn.FinishLoginResponse, error)
}

// NewWebAuthnServiceClient constructs a client for the services.WebAuthnService service. Multiple
// service clients may share a single connect.Client.
func NewWebAuthnServiceClient(client *connect.Client) WebAuthnServiceClient {
	return &webAuthnServiceClient{client: client}
}

// WebAuthnServiceHandler is an implementation of the services.WebAuthnService service.
type WebAuthnServiceHandler interface {
	// Begin the webauthn registration ceremony
	BeginRegister(context.Context, *webauthn.BeginRegisterRequest) (*webauthn.BeginRegisterResponse, error)
	// Finish the webauthn registration ceremony
	FinishRegister(context.Context, *webauthn.FinishRegisterRequest) (*webauthn.FinishRegisterResponse, error)
	// Begin the webauthn login ceremony
	BeginLogin(context.Context, *webauthn.BeginLoginRequest) (*webauthn.BeginLoginResponse, error)
	// Finish the webauthn login ceremony
	FinishLogin(context.Context, *webauthn.FinishLoginRequest) (*webauthn.FinishLoginResponse, error)
}

// RegisterWebAuthnServiceHandler registers svc as the services.WebAuthnService implementation on
// server.
func RegisterWebAuthnServiceHandler(server *connect.Server, svc WebAuthnServiceHandler) {
	adapter := webAuthnServiceHandler{svc: svc}
	server.Register(
		connect.Method{Spec: webAuthnServiceBeginRegisterSpec(), Handler: adapter.beginRegister},
		connect.Method{Spec: webAuthnServiceFinishRegisterSpec(), Handler: adapter.finishRegister},
		connect.Method{Spec: webAuthnServiceBeginLoginSpec(), Handler: adapter.beginLogin},
		connect.Method{Spec: webAuthnServiceFinishLoginSpec(), Handler: adapter.finishLogin},
	)
}

// UnimplementedWebAuthnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWebAuthnServiceHandler struct{}

func (UnimplementedWebAuthnServiceHandler) BeginRegister(context.Context, *webauthn.BeginRegisterRequest) (*webauthn.BeginRegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.WebAuthnService.BeginRegister is not implemented")
}

func (UnimplementedWebAuthnServiceHandler) FinishRegister(context.Context, *webauthn.FinishRegisterRequest) (*webauthn.FinishRegisterResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.WebAuthnService.FinishRegister is not implemented")
}

func (UnimplementedWebAuthnServiceHandler) BeginLogin(context.Context, *webauthn.BeginLoginRequest) (*webauthn.BeginLoginResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.WebAuthnService.BeginLogin is not implemented")
}

func (UnimplementedWebAuthnServiceHandler) FinishLogin(context.Context, *webauthn.FinishLoginRequest) (*webauthn.FinishLoginResponse, error) {
	return nil, connect.NewError(connect.CodeUnimplemented, "services.WebAuthnService.FinishLogin is not implemented")
}

type webAuthnServiceClient struct {
	client *connect.Client
}

func (c *webAuthnServiceClient) BeginRegister(ctx context.Context, req *webauthn.BeginRegisterRequest) (*webauthn.BeginRegisterResponse, error) {
	var res webauthn.BeginRegisterResponse
	if err := c.client.CallUnary(ctx, webAuthnServiceBeginRegisterSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *webAuthnServiceClient) FinishRegister(ctx context.Context, req *webauthn.FinishRegisterRequest) (*webauthn.FinishRegisterResponse, error) {
	var res webauthn.FinishRegisterResponse
	if err := c.client.CallUnary(ctx, webAuthnServiceFinishRegisterSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *webAuthnServiceClient) BeginLogin(ctx context.Context, req *webauthn.BeginLoginRequest) (*webauthn.BeginLoginResponse, error) {
	var res webauthn.BeginLoginResponse
	if err := c.client.CallUnary(ctx, webAuthnServiceBeginLoginSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

func (c *webAuthnServiceClient) FinishLogin(ctx context.Context, req *webauthn.FinishLoginRequest) (*webauthn.FinishLoginResponse, error) {
	var res webauthn.FinishLoginResponse
	if err := c.client.CallUnary(ctx, webAuthnServiceFinishLoginSpec(), req, &res); err != nil {
		return nil, err
	}
	return &res, nil
}

type webAuthnServiceHandler struct{ svc WebAuthnServiceHandler }

func (h webAuthnServiceHandler) beginRegister(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req webauthn.BeginRegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.BeginRegister(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h webAuthnServiceHandler) finishRegister(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req webauthn.FinishRegisterRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.FinishRegister(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h webAuthnServiceHandler) beginLogin(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req webauthn.BeginLoginRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.BeginLogin(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}

func (h webAuthnServiceHandler) finishLogin(ctx context.Context, _ connect.Spec, stream connect.ServerStream) error {
	var req webauthn.FinishLoginRequest
	if err := stream.Receive(&req); err != nil {
		return err
	}
	res, err := h.svc.FinishLogin(ctx, &req)
	if err != nil {
		return err
	}
	return stream.Send(res)
}
