// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: services/webauthn.proto

package servicesconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	services "github.com/authaas/api/services"
	webauthn "github.com/authaas/api/webauthn"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WebAuthnServiceName is the fully-qualified name of the WebAuthnService service.
	WebAuthnServiceName = "services.WebAuthnService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WebAuthnServiceBeginRegisterProcedure is the fully-qualified name of the WebAuthnService's
	// BeginRegister RPC.
	WebAuthnServiceBeginRegisterProcedure = "/services.WebAuthnService/BeginRegister"
	// WebAuthnServiceFinishRegisterProcedure is the fully-qualified name of the WebAuthnService's
	// FinishRegister RPC.
	WebAuthnServiceFinishRegisterProcedure = "/services.WebAuthnService/FinishRegister"
	// WebAuthnServiceBeginLoginProcedure is the fully-qualified name of the WebAuthnService's
	// BeginLogin RPC.
	WebAuthnServiceBeginLoginProcedure = "/services.WebAuthnService/BeginLogin"
	// WebAuthnServiceFinishLoginProcedure is the fully-qualified name of the WebAuthnService's
	// FinishLogin RPC.
	WebAuthnServiceFinishLoginProcedure = "/services.WebAuthnService/FinishLogin"
)

// WebAuthnServiceClient is a client for the services.WebAuthnService service.
type WebAuthnServiceClient interface {
	// Begin the webauthn registration ceremony
	BeginRegister(context.Context, *connect.Request[webauthn.BeginRegisterRequest]) (*connect.Response[webauthn.BeginRegisterResponse], error)
	// Finish the webauthn registration ceremony
	FinishRegister(context.Context, *connect.Request[webauthn.FinishRegisterRequest]) (*connect.Response[webauthn.FinishRegisterResponse], error)
	// Begin the webauthn login ceremony
	BeginLogin(context.Context, *connect.Request[webauthn.BeginLoginRequest]) (*connect.Response[webauthn.BeginLoginResponse], error)
	// Finish the webauthn login ceremony
	FinishLogin(context.Context, *connect.Request[webauthn.FinishLoginRequest]) (*connect.Response[webauthn.FinishLoginResponse], error)
}

// NewWebAuthnServiceClient constructs a client for the services.WebAuthnService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWebAuthnServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WebAuthnServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	webAuthnServiceMethods := services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods()
	return &webAuthnServiceClient{
		beginRegister: connect.NewClient[webauthn.BeginRegisterRequest, webauthn.BeginRegisterResponse](
			httpClient,
			baseURL+WebAuthnServiceBeginRegisterProcedure,
			connect.WithSchema(webAuthnServiceMethods.ByName("BeginRegister")),
			connect.WithClientOptions(opts...),
		),
		finishRegister: connect.NewClient[webauthn.FinishRegisterRequest, webauthn.FinishRegisterResponse](
			httpClient,
			baseURL+WebAuthnServiceFinishRegisterProcedure,
			connect.WithSchema(webAuthnServiceMethods.ByName("FinishRegister")),
			connect.WithClientOptions(opts...),
		),
		beginLogin: connect.NewClient[webauthn.BeginLoginRequest, webauthn.BeginLoginResponse](
			httpClient,
			baseURL+WebAuthnServiceBeginLoginProcedure,
			connect.WithSchema(webAuthnServiceMethods.ByName("BeginLogin")),
			connect.WithClientOptions(opts...),
		),
		finishLogin: connect.NewClient[webauthn.FinishLoginRequest, webauthn.FinishLoginResponse](
			httpClient,
			baseURL+WebAuthnServiceFinishLoginProcedure,
			connect.WithSchema(webAuthnServiceMethods.ByName("FinishLogin")),
			connect.WithClientOptions(opts...),
		),
	}
}

// webAuthnServiceClient implements WebAuthnServiceClient.
type webAuthnServiceClient struct {
	beginRegister  *connect.Client[webauthn.BeginRegisterRequest, webauthn.BeginRegisterResponse]
	finishRegister *connect.Client[webauthn.FinishRegisterRequest, webauthn.FinishRegisterResponse]
	beginLogin     *connect.Client[webauthn.BeginLoginRequest, webauthn.BeginLoginResponse]
	finishLogin    *connect.Client[webauthn.FinishLoginRequest, webauthn.FinishLoginResponse]
}

// BeginRegister calls services.WebAuthnService.BeginRegister.
func (c *webAuthnServiceClient) BeginRegister(ctx context.Context, req *connect.Request[webauthn.BeginRegisterRequest]) (*connect.Response[webauthn.BeginRegisterResponse], error) {
	return c.beginRegister.CallUnary(ctx, req)
}

// FinishRegister calls services.WebAuthnService.FinishRegister.
func (c *webAuthnServiceClient) FinishRegister(ctx context.Context, req *connect.Request[webauthn.FinishRegisterRequest]) (*connect.Response[webauthn.FinishRegisterResponse], error) {
	return c.finishRegister.CallUnary(ctx, req)
}

// BeginLogin calls services.WebAuthnService.BeginLogin.
func (c *webAuthnServiceClient) BeginLogin(ctx context.Context, req *connect.Request[webauthn.BeginLoginRequest]) (*connect.Response[webauthn.BeginLoginResponse], error) {
	return c.beginLogin.CallUnary(ctx, req)
}

// FinishLogin calls services.WebAuthnService.FinishLogin.
func (c *webAuthnServiceClient) FinishLogin(ctx context.Context, req *connect.Request[webauthn.FinishLoginRequest]) (*connect.Response[webauthn.FinishLoginResponse], error) {
	return c.finishLogin.CallUnary(ctx, req)
}

// WebAuthnServiceHandler is an implementation of the services.WebAuthnService service.
type WebAuthnServiceHandler interface {
	// Begin the webauthn registration ceremony
	BeginRegister(context.Context, *connect.Request[webauthn.BeginRegisterRequest]) (*connect.Response[webauthn.BeginRegisterResponse], error)
	// Finish the webauthn registration ceremony
	FinishRegister(context.Context, *connect.Request[webauthn.FinishRegisterRequest]) (*connect.Response[webauthn.FinishRegisterResponse], error)
	// Begin the webauthn login ceremony
	BeginLogin(context.Context, *connect.Request[webauthn.BeginLoginRequest]) (*connect.Response[webauthn.BeginLoginResponse], error)
	// Finish the webauthn login ceremony
	FinishLogin(context.Context, *connect.Request[webauthn.FinishLoginRequest]) (*connect.Response[webauthn.FinishLoginResponse], error)
}

// NewWebAuthnServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWebAuthnServiceHandler(svc WebAuthnServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	webAuthnServiceMethods := services.File_services_webauthn_proto.Services().ByName("WebAuthnService").Methods()
	webAuthnServiceBeginRegisterHandler := connect.NewUnaryHandler(
		WebAuthnServiceBeginRegisterProcedure,
		svc.BeginRegister,
		connect.WithSchema(webAuthnServiceMethods.ByName("BeginRegister")),
		connect.WithHandlerOptions(opts...),
	)
	webAuthnServiceFinishRegisterHandler := connect.NewUnaryHandler(
		WebAuthnServiceFinishRegisterProcedure,
		svc.FinishRegister,
		connect.WithSchema(webAuthnServiceMethods.ByName("FinishRegister")),
		connect.WithHandlerOptions(opts...),
	)
	webAuthnServiceBeginLoginHandler := connect.NewUnaryHandler(
		WebAuthnServiceBeginLoginProcedure,
		svc.BeginLogin,
		connect.WithSchema(webAuthnServiceMethods.ByName("BeginLogin")),
		connect.WithHandlerOptions(opts...),
	)
	webAuthnServiceFinishLoginHandler := connect.NewUnaryHandler(
		WebAuthnServiceFinishLoginProcedure,
		svc.FinishLogin,
		connect.WithSchema(webAuthnServiceMethods.ByName("FinishLogin")),
		connect.WithHandlerOptions(opts...),
	)
	return "/services.WebAuthnService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WebAuthnServiceBeginRegisterProcedure:
			webAuthnServiceBeginRegisterHandler.ServeHTTP(w, r)
		case WebAuthnServiceFinishRegisterProcedure:
			webAuthnServiceFinishRegisterHandler.ServeHTTP(w, r)
		case WebAuthnServiceBeginLoginProcedure:
			webAuthnServiceBeginLoginHandler.ServeHTTP(w, r)
		case WebAuthnServiceFinishLoginProcedure:
			webAuthnServiceFinishLoginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWebAuthnServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWebAuthnServiceHandler struct{}

func (UnimplementedWebAuthnServiceHandler) BeginRegister(context.Context, *connect.Request[webauthn.BeginRegisterRequest]) (*connect.Response[webauthn.BeginRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.WebAuthnService.BeginRegister is not implemented"))
}

func (UnimplementedWebAuthnServiceHandler) FinishRegister(context.Context, *connect.Request[webauthn.FinishRegisterRequest]) (*connect.Response[webauthn.FinishRegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.WebAuthnService.FinishRegister is not implemented"))
}

func (UnimplementedWebAuthnServiceHandler) BeginLogin(context.Context, *connect.Request[webauthn.BeginLoginRequest]) (*connect.Response[webauthn.BeginLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.WebAuthnService.BeginLogin is not implemented"))
}

func (UnimplementedWebAuthnServiceHandler) FinishLogin(context.Context, *connect.Request[webauthn.FinishLoginRequest]) (*connect.Response[webauthn.FinishLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("services.WebAuthnService.FinishLogin is not implemented"))
}
