// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/login.proto

package webauthn

import (
	identity "github.com/authaas/api/identity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssertionCredential struct {
	state                   protoimpl.MessageState          `protogen:"open.v1"`
	RawId                   []byte                          `protobuf:"bytes,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	Type                    PublicKeyCredentialType         `protobuf:"varint,2,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	AuthenticatorAttachment AuthenticatorAttachment         `protobuf:"varint,3,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3,enum=webauthn.AuthenticatorAttachment" json:"authenticator_attachment,omitempty"`
	ClientExtensionResults  []byte                          `protobuf:"bytes,4,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	Response                *AuthenticatorAssertionResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AssertionCredential) Reset() {
	*x = AssertionCredential{}
	mi := &file_webauthn_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssertionCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssertionCredential) ProtoMessage() {}

func (x *AssertionCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssertionCredential.ProtoReflect.Descriptor instead.
func (*AssertionCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{0}
}

func (x *AssertionCredential) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *AssertionCredential) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *AssertionCredential) GetAuthenticatorAttachment() AuthenticatorAttachment {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED
}

func (x *AssertionCredential) GetClientExtensionResults() []byte {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

func (x *AssertionCredential) GetResponse() *AuthenticatorAssertionResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type PublicKeyCredentialRequestOptions struct {
	state            protoimpl.MessageState           `protogen:"open.v1"`
	Challenge        []byte                           `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Timeout          uint32                           `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	RpId             string                           `protobuf:"bytes,3,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	AllowCredentials []*PublicKeyCredentialDescriptor `protobuf:"bytes,4,rep,name=allow_credentials,json=allowCredentials,proto3" json:"allow_credentials,omitempty"`
	UserVerification UserVerificationRequirement      `protobuf:"varint,5,opt,name=user_verification,json=userVerification,proto3,enum=webauthn.UserVerificationRequirement" json:"user_verification,omitempty"`
	Hints            []string                         `protobuf:"bytes,6,rep,name=hints,proto3" json:"hints,omitempty"`
	Extensions       []byte                           `protobuf:"bytes,7,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PublicKeyCredentialRequestOptions) Reset() {
	*x = PublicKeyCredentialRequestOptions{}
	mi := &file_webauthn_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialRequestOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialRequestOptions) ProtoMessage() {}

func (x *PublicKeyCredentialRequestOptions) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialRequestOptions.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialRequestOptions) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeyCredentialRequestOptions) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PublicKeyCredentialRequestOptions) GetRpId() string {
	if x != nil {
		return x.RpId
	}
	return ""
}

func (x *PublicKeyCredentialRequestOptions) GetAllowCredentials() []*PublicKeyCredentialDescriptor {
	if x != nil {
		return x.AllowCredentials
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetUserVerification() UserVerificationRequirement {
	if x != nil {
		return x.UserVerification
	}
	return UserVerificationRequirement_USER_VERIFICATION_REQUIREMENT_UNSPECIFIED
}

func (x *PublicKeyCredentialRequestOptions) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *PublicKeyCredentialRequestOptions) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type BeginLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  []byte                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginRequest) Reset() {
	*x = BeginLoginRequest{}
	mi := &file_webauthn_login_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginRequest) ProtoMessage() {}

func (x *BeginLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginRequest.ProtoReflect.Descriptor instead.
func (*BeginLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{2}
}

func (x *BeginLoginRequest) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

type BeginLoginResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Options       *PublicKeyCredentialRequestOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginLoginResponse) Reset() {
	*x = BeginLoginResponse{}
	mi := &file_webauthn_login_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginLoginResponse) ProtoMessage() {}

func (x *BeginLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginLoginResponse.ProtoReflect.Descriptor instead.
func (*BeginLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{3}
}

func (x *BeginLoginResponse) GetOptions() *PublicKeyCredentialRequestOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type FinishLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *AssertionCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginRequest) Reset() {
	*x = FinishLoginRequest{}
	mi := &file_webauthn_login_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginRequest) ProtoMessage() {}

func (x *FinishLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginRequest.ProtoReflect.Descriptor instead.
func (*FinishLoginRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{4}
}

func (x *FinishLoginRequest) GetCredential() *AssertionCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type FinishLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *identity.Proof        `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishLoginResponse) Reset() {
	*x = FinishLoginResponse{}
	mi := &file_webauthn_login_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishLoginResponse) ProtoMessage() {}

func (x *FinishLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_login_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishLoginResponse.ProtoReflect.Descriptor instead.
func (*FinishLoginResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_login_proto_rawDescGZIP(), []int{5}
}

func (x *FinishLoginResponse) GetProof() *identity.Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_webauthn_login_proto protoreflect.FileDescriptor

const file_webauthn_login_proto_rawDesc = "" +
	"\n" +
	"\x14webauthn/login.proto\x12\bwebauthn\x1a\x14identity/proof.proto\x1a\x1cwebauthn/authenticator.proto\x1a$webauthn/public_key_credential.proto\"\xc1\x02\n" +
	"\x13AssertionCredential\x12\x15\n" +
	"\x06raw_id\x18\x01 \x01(\fR\x05rawId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12\\\n" +
	"\x18authenticator_attachment\x18\x03 \x01(\x0e2!.webauthn.AuthenticatorAttachmentR\x17authenticatorAttachment\x128\n" +
	"\x18client_extension_results\x18\x04 \x01(\fR\x16clientExtensionResults\x12D\n" +
	"\bresponse\x18\x05 \x01(\v2(.webauthn.AuthenticatorAssertionResponseR\bresponse\"\xd0\x02\n" +
	"!PublicKeyCredentialRequestOptions\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\rR\atimeout\x12\x13\n" +
	"\x05rp_id\x18\x03 \x01(\tR\x04rpId\x12T\n" +
	"\x11allow_credentials\x18\x04 \x03(\v2'.webauthn.PublicKeyCredentialDescriptorR\x10allowCredentials\x12R\n" +
	"\x11user_verification\x18\x05 \x01(\x0e2%.webauthn.UserVerificationRequirementR\x10userVerification\x12\x14\n" +
	"\x05hints\x18\x06 \x03(\tR\x05hints\x12\x1e\n" +
	"\n" +
	"extensions\x18\a \x01(\fR\n" +
	"extensions\"8\n" +
	"\x11BeginLoginRequest\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\fR\fcredentialId\"[\n" +
	"\x12BeginLoginResponse\x12E\n" +
	"\aoptions\x18\x01 \x01(\v2+.webauthn.PublicKeyCredentialRequestOptionsR\aoptions\"S\n" +
	"\x12FinishLoginRequest\x12=\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1d.webauthn.AssertionCredentialR\n" +
	"credential\"<\n" +
	"\x13FinishLoginResponse\x12%\n" +
	"\x05proof\x18\x01 \x01(\v2\x0f.identity.ProofR\x05proofB!Z\x1fgithub.com/authaas/api/webauthnb\x06proto3"

var (
	file_webauthn_login_proto_rawDescOnce sync.Once
	file_webauthn_login_proto_rawDescData []byte
)

func file_webauthn_login_proto_rawDescGZIP() []byte {
	file_webauthn_login_proto_rawDescOnce.Do(func() {
		file_webauthn_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_login_proto_rawDesc), len(file_webauthn_login_proto_rawDesc)))
	})
	return file_webauthn_login_proto_rawDescData
}

var file_webauthn_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webauthn_login_proto_goTypes = []any{
	(*AssertionCredential)(nil),               // 0: webauthn.AssertionCredential
	(*PublicKeyCredentialRequestOptions)(nil), // 1: webauthn.PublicKeyCredentialRequestOptions
	(*BeginLoginRequest)(nil),                 // 2: webauthn.BeginLoginRequest
	(*BeginLoginResponse)(nil),                // 3: webauthn.BeginLoginResponse
	(*FinishLoginRequest)(nil),                // 4: webauthn.FinishLoginRequest
	(*FinishLoginResponse)(nil),               // 5: webauthn.FinishLoginResponse
	(PublicKeyCredentialType)(0),              // 6: webauthn.PublicKeyCredentialType
	(AuthenticatorAttachment)(0),              // 7: webauthn.AuthenticatorAttachment
	(*AuthenticatorAssertionResponse)(nil),    // 8: webauthn.AuthenticatorAssertionResponse
	(*PublicKeyCredentialDescriptor)(nil),     // 9: webauthn.PublicKeyCredentialDescriptor
	(UserVerificationRequirement)(0),          // 10: webauthn.UserVerificationRequirement
	(*identity.Proof)(nil),                    // 11: identity.Proof
}
var file_webauthn_login_proto_depIdxs = []int32{
	6,  // 0: webauthn.AssertionCredential.type:type_name -> webauthn.PublicKeyCredentialType
	7,  // 1: webauthn.AssertionCredential.authenticator_attachment:type_name -> webauthn.AuthenticatorAttachment
	8,  // 2: webauthn.AssertionCredential.response:type_name -> webauthn.AuthenticatorAssertionResponse
	9,  // 3: webauthn.PublicKeyCredentialRequestOptions.allow_credentials:type_name -> webauthn.PublicKeyCredentialDescriptor
	10, // 4: webauthn.PublicKeyCredentialRequestOptions.user_verification:type_name -> webauthn.UserVerificationRequirement
	1,  // 5: webauthn.BeginLoginResponse.options:type_name -> webauthn.PublicKeyCredentialRequestOptions
	0,  // 6: webauthn.FinishLoginRequest.credential:type_name -> webauthn.AssertionCredential
	11, // 7: webauthn.FinishLoginResponse.proof:type_name -> identity.Proof
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_webauthn_login_proto_init() }
func file_webauthn_login_proto_init() {
	if File_webauthn_login_proto != nil {
		return
	}
	file_webauthn_authenticator_proto_init()
	file_webauthn_public_key_credential_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_login_proto_rawDesc), len(file_webauthn_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_login_proto_goTypes,
		DependencyIndexes: file_webauthn_login_proto_depIdxs,
		MessageInfos:      file_webauthn_login_proto_msgTypes,
	}.Build()
	File_webauthn_login_proto = out.File
	file_webauthn_login_proto_goTypes = nil
	file_webauthn_login_proto_depIdxs = nil
}
