// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: webauthn/register.proto

package webauthn

import (
	identity "github.com/authaas/api/identity"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttestationCredential struct {
	state                   protoimpl.MessageState            `protogen:"open.v1"`
	RawId                   []byte                            `protobuf:"bytes,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	Type                    PublicKeyCredentialType           `protobuf:"varint,2,opt,name=type,proto3,enum=webauthn.PublicKeyCredentialType" json:"type,omitempty"`
	AuthenticatorAttachment AuthenticatorAttachment           `protobuf:"varint,3,opt,name=authenticator_attachment,json=authenticatorAttachment,proto3,enum=webauthn.AuthenticatorAttachment" json:"authenticator_attachment,omitempty"`
	ClientExtensionResults  []byte                            `protobuf:"bytes,4,opt,name=client_extension_results,json=clientExtensionResults,proto3" json:"client_extension_results,omitempty"`
	Response                *AuthenticatorAttestationResponse `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AttestationCredential) Reset() {
	*x = AttestationCredential{}
	mi := &file_webauthn_register_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttestationCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttestationCredential) ProtoMessage() {}

func (x *AttestationCredential) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttestationCredential.ProtoReflect.Descriptor instead.
func (*AttestationCredential) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{0}
}

func (x *AttestationCredential) GetRawId() []byte {
	if x != nil {
		return x.RawId
	}
	return nil
}

func (x *AttestationCredential) GetType() PublicKeyCredentialType {
	if x != nil {
		return x.Type
	}
	return PublicKeyCredentialType_PUBLIC_KEY_CREDENTIAL_TYPE_UNSPECIFIED
}

func (x *AttestationCredential) GetAuthenticatorAttachment() AuthenticatorAttachment {
	if x != nil {
		return x.AuthenticatorAttachment
	}
	return AuthenticatorAttachment_AUTHENTICATOR_ATTACHMENT_UNSPECIFIED
}

func (x *AttestationCredential) GetClientExtensionResults() []byte {
	if x != nil {
		return x.ClientExtensionResults
	}
	return nil
}

func (x *AttestationCredential) GetResponse() *AuthenticatorAttestationResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type PublicKeyCredentialCreationOptions struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	Challenge              []byte                           `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	Timeout                uint32                           `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Rp                     *PublicKeyCredentialRpEntity     `protobuf:"bytes,3,opt,name=rp,proto3" json:"rp,omitempty"`
	User                   *identity.Principal              `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	PubKeyCredParams       []*PublicKeyCredentialParameters `protobuf:"bytes,5,rep,name=pub_key_cred_params,json=pubKeyCredParams,proto3" json:"pub_key_cred_params,omitempty"`
	ExcludeCredentials     []*PublicKeyCredentialDescriptor `protobuf:"bytes,6,rep,name=exclude_credentials,json=excludeCredentials,proto3" json:"exclude_credentials,omitempty"`
	AuthenticatorSelection *AuthenticatorSelectionCriteria  `protobuf:"bytes,7,opt,name=authenticator_selection,json=authenticatorSelection,proto3" json:"authenticator_selection,omitempty"`
	Hints                  []string                         `protobuf:"bytes,8,rep,name=hints,proto3" json:"hints,omitempty"`
	Attestation            AttestationConveyancePreference  `protobuf:"varint,9,opt,name=attestation,proto3,enum=webauthn.AttestationConveyancePreference" json:"attestation,omitempty"`
	AttestationFormats     []string                         `protobuf:"bytes,10,rep,name=attestation_formats,json=attestationFormats,proto3" json:"attestation_formats,omitempty"`
	Extensions             []byte                           `protobuf:"bytes,11,opt,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PublicKeyCredentialCreationOptions) Reset() {
	*x = PublicKeyCredentialCreationOptions{}
	mi := &file_webauthn_register_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeyCredentialCreationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeyCredentialCreationOptions) ProtoMessage() {}

func (x *PublicKeyCredentialCreationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeyCredentialCreationOptions.ProtoReflect.Descriptor instead.
func (*PublicKeyCredentialCreationOptions) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeyCredentialCreationOptions) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetTimeout() uint32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *PublicKeyCredentialCreationOptions) GetRp() *PublicKeyCredentialRpEntity {
	if x != nil {
		return x.Rp
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetUser() *identity.Principal {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetPubKeyCredParams() []*PublicKeyCredentialParameters {
	if x != nil {
		return x.PubKeyCredParams
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetExcludeCredentials() []*PublicKeyCredentialDescriptor {
	if x != nil {
		return x.ExcludeCredentials
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetAuthenticatorSelection() *AuthenticatorSelectionCriteria {
	if x != nil {
		return x.AuthenticatorSelection
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetHints() []string {
	if x != nil {
		return x.Hints
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetAttestation() AttestationConveyancePreference {
	if x != nil {
		return x.Attestation
	}
	return AttestationConveyancePreference_ATTESTATION_CONVEYANCE_PREFERENCE_UNSPECIFIED
}

func (x *PublicKeyCredentialCreationOptions) GetAttestationFormats() []string {
	if x != nil {
		return x.AttestationFormats
	}
	return nil
}

func (x *PublicKeyCredentialCreationOptions) GetExtensions() []byte {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type BeginRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegisterRequest) Reset() {
	*x = BeginRegisterRequest{}
	mi := &file_webauthn_register_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegisterRequest) ProtoMessage() {}

func (x *BeginRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegisterRequest.ProtoReflect.Descriptor instead.
func (*BeginRegisterRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{2}
}

func (x *BeginRegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeginRegisterRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type BeginRegisterResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Options       *PublicKeyCredentialCreationOptions `protobuf:"bytes,1,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginRegisterResponse) Reset() {
	*x = BeginRegisterResponse{}
	mi := &file_webauthn_register_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginRegisterResponse) ProtoMessage() {}

func (x *BeginRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginRegisterResponse.ProtoReflect.Descriptor instead.
func (*BeginRegisterResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{3}
}

func (x *BeginRegisterResponse) GetOptions() *PublicKeyCredentialCreationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type FinishRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *identity.Principal    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Credential    *AttestationCredential `protobuf:"bytes,2,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegisterRequest) Reset() {
	*x = FinishRegisterRequest{}
	mi := &file_webauthn_register_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegisterRequest) ProtoMessage() {}

func (x *FinishRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegisterRequest.ProtoReflect.Descriptor instead.
func (*FinishRegisterRequest) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{4}
}

func (x *FinishRegisterRequest) GetUser() *identity.Principal {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *FinishRegisterRequest) GetCredential() *AttestationCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type FinishRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proof         *identity.Proof        `protobuf:"bytes,1,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishRegisterResponse) Reset() {
	*x = FinishRegisterResponse{}
	mi := &file_webauthn_register_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishRegisterResponse) ProtoMessage() {}

func (x *FinishRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webauthn_register_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishRegisterResponse.ProtoReflect.Descriptor instead.
func (*FinishRegisterResponse) Descriptor() ([]byte, []int) {
	return file_webauthn_register_proto_rawDescGZIP(), []int{5}
}

func (x *FinishRegisterResponse) GetProof() *identity.Proof {
	if x != nil {
		return x.Proof
	}
	return nil
}

var File_webauthn_register_proto protoreflect.FileDescriptor

const file_webauthn_register_proto_rawDesc = "" +
	"\n" +
	"\x17webauthn/register.proto\x12\bwebauthn\x1a\x18identity/principal.proto\x1a\x14identity/proof.proto\x1a\x1cwebauthn/authenticator.proto\x1a$webauthn/public_key_credential.proto\x1a\x1cwebauthn/relying_party.proto\"\xc5\x02\n" +
	"\x15AttestationCredential\x12\x15\n" +
	"\x06raw_id\x18\x01 \x01(\fR\x05rawId\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2!.webauthn.PublicKeyCredentialTypeR\x04type\x12\\\n" +
	"\x18authenticator_attachment\x18\x03 \x01(\x0e2!.webauthn.AuthenticatorAttachmentR\x17authenticatorAttachment\x128\n" +
	"\x18client_extension_results\x18\x04 \x01(\fR\x16clientExtensionResults\x12F\n" +
	"\bresponse\x18\x05 \x01(\v2*.webauthn.AuthenticatorAttestationResponseR\bresponse\"\x85\x05\n" +
	"\"PublicKeyCredentialCreationOptions\x12\x1c\n" +
	"\tchallenge\x18\x01 \x01(\fR\tchallenge\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\rR\atimeout\x125\n" +
	"\x02rp\x18\x03 \x01(\v2%.webauthn.PublicKeyCredentialRpEntityR\x02rp\x12'\n" +
	"\x04user\x18\x04 \x01(\v2\x13.identity.PrincipalR\x04user\x12V\n" +
	"\x13pub_key_cred_params\x18\x05 \x03(\v2'.webauthn.PublicKeyCredentialParametersR\x10pubKeyCredParams\x12X\n" +
	"\x13exclude_credentials\x18\x06 \x03(\v2'.webauthn.PublicKeyCredentialDescriptorR\x12excludeCredentials\x12a\n" +
	"\x17authenticator_selection\x18\a \x01(\v2(.webauthn.AuthenticatorSelectionCriteriaR\x16authenticatorSelection\x12\x14\n" +
	"\x05hints\x18\b \x03(\tR\x05hints\x12K\n" +
	"\vattestation\x18\t \x01(\x0e2).webauthn.AttestationConveyancePreferenceR\vattestation\x12/\n" +
	"\x13attestation_formats\x18\n" +
	" \x03(\tR\x12attestationFormats\x12\x1e\n" +
	"\n" +
	"extensions\x18\v \x01(\fR\n" +
	"extensions\"M\n" +
	"\x14BeginRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"_\n" +
	"\x15BeginRegisterResponse\x12F\n" +
	"\aoptions\x18\x01 \x01(\v2,.webauthn.PublicKeyCredentialCreationOptionsR\aoptions\"\x81\x01\n" +
	"\x15FinishRegisterRequest\x12'\n" +
	"\x04user\x18\x01 \x01(\v2\x13.identity.PrincipalR\x04user\x12?\n" +
	"\n" +
	"credential\x18\x02 \x01(\v2\x1f.webauthn.AttestationCredentialR\n" +
	"credential\"?\n" +
	"\x16FinishRegisterResponse\x12%\n" +
	"\x05proof\x18\x01 \x01(\v2\x0f.identity.ProofR\x05proofB!Z\x1fgithub.com/authaas/api/webauthnb\x06proto3"

var (
	file_webauthn_register_proto_rawDescOnce sync.Once
	file_webauthn_register_proto_rawDescData []byte
)

func file_webauthn_register_proto_rawDescGZIP() []byte {
	file_webauthn_register_proto_rawDescOnce.Do(func() {
		file_webauthn_register_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webauthn_register_proto_rawDesc), len(file_webauthn_register_proto_rawDesc)))
	})
	return file_webauthn_register_proto_rawDescData
}

var file_webauthn_register_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_webauthn_register_proto_goTypes = []any{
	(*AttestationCredential)(nil),              // 0: webauthn.AttestationCredential
	(*PublicKeyCredentialCreationOptions)(nil), // 1: webauthn.PublicKeyCredentialCreationOptions
	(*BeginRegisterRequest)(nil),               // 2: webauthn.BeginRegisterRequest
	(*BeginRegisterResponse)(nil),              // 3: webauthn.BeginRegisterResponse
	(*FinishRegisterRequest)(nil),              // 4: webauthn.FinishRegisterRequest
	(*FinishRegisterResponse)(nil),             // 5: webauthn.FinishRegisterResponse
	(PublicKeyCredentialType)(0),               // 6: webauthn.PublicKeyCredentialType
	(AuthenticatorAttachment)(0),               // 7: webauthn.AuthenticatorAttachment
	(*AuthenticatorAttestationResponse)(nil),   // 8: webauthn.AuthenticatorAttestationResponse
	(*PublicKeyCredentialRpEntity)(nil),        // 9: webauthn.PublicKeyCredentialRpEntity
	(*identity.Principal)(nil),                 // 10: identity.Principal
	(*PublicKeyCredentialParameters)(nil),      // 11: webauthn.PublicKeyCredentialParameters
	(*PublicKeyCredentialDescriptor)(nil),      // 12: webauthn.PublicKeyCredentialDescriptor
	(*AuthenticatorSelectionCriteria)(nil),     // 13: webauthn.AuthenticatorSelectionCriteria
	(AttestationConveyancePreference)(0),       // 14: webauthn.AttestationConveyancePreference
	(*identity.Proof)(nil),                     // 15: identity.Proof
}
var file_webauthn_register_proto_depIdxs = []int32{
	6,  // 0: webauthn.AttestationCredential.type:type_name -> webauthn.PublicKeyCredentialType
	7,  // 1: webauthn.AttestationCredential.authenticator_attachment:type_name -> webauthn.AuthenticatorAttachment
	8,  // 2: webauthn.AttestationCredential.response:type_name -> webauthn.AuthenticatorAttestationResponse
	9,  // 3: webauthn.PublicKeyCredentialCreationOptions.rp:type_name -> webauthn.PublicKeyCredentialRpEntity
	10, // 4: webauthn.PublicKeyCredentialCreationOptions.user:type_name -> identity.Principal
	11, // 5: webauthn.PublicKeyCredentialCreationOptions.pub_key_cred_params:type_name -> webauthn.PublicKeyCredentialParameters
	12, // 6: webauthn.PublicKeyCredentialCreationOptions.exclude_credentials:type_name -> webauthn.PublicKeyCredentialDescriptor
	13, // 7: webauthn.PublicKeyCredentialCreationOptions.authenticator_selection:type_name -> webauthn.AuthenticatorSelectionCriteria
	14, // 8: webauthn.PublicKeyCredentialCreationOptions.attestation:type_name -> webauthn.AttestationConveyancePreference
	1,  // 9: webauthn.BeginRegisterResponse.options:type_name -> webauthn.PublicKeyCredentialCreationOptions
	10, // 10: webauthn.FinishRegisterRequest.user:type_name -> identity.Principal
	0,  // 11: webauthn.FinishRegisterRequest.credential:type_name -> webauthn.AttestationCredential
	15, // 12: webauthn.FinishRegisterResponse.proof:type_name -> identity.Proof
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_webauthn_register_proto_init() }
func file_webauthn_register_proto_init() {
	if File_webauthn_register_proto != nil {
		return
	}
	file_webauthn_authenticator_proto_init()
	file_webauthn_public_key_credential_proto_init()
	file_webauthn_relying_party_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webauthn_register_proto_rawDesc), len(file_webauthn_register_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webauthn_register_proto_goTypes,
		DependencyIndexes: file_webauthn_register_proto_depIdxs,
		MessageInfos:      file_webauthn_register_proto_msgTypes,
	}.Build()
	File_webauthn_register_proto = out.File
	file_webauthn_register_proto_goTypes = nil
	file_webauthn_register_proto_depIdxs = nil
}
