syntax = "proto3";

package webauthn;

import "token/proof.proto";
import "webauthn/authenticator.proto";
import "webauthn/public_key_credential.proto";

option go_package = "github.com/authaas/api/webauthn";

message AssertionCredential {
  bytes raw_id = 1;
  PublicKeyCredentialType type = 2;
  AuthenticatorAttachment authenticator_attachment = 3;
  bytes client_extension_results = 4;
  AuthenticatorAssertionResponse response = 5;
}

message PublicKeyCredentialRequestOptions {
  bytes challenge = 1;
  uint32 timeout = 2;
  string rp_id = 3;
  repeated PublicKeyCredentialDescriptor allow_credentials = 4;
  UserVerificationRequirement user_verification = 5;
  repeated string hints = 6;
  bytes extensions = 7;
}

message BeginLoginRequest {}

message BeginLoginResponse {
  PublicKeyCredentialRequestOptions options = 1;
}

message FinishLoginRequest {
  AssertionCredential credential = 1;
}

message FinishLoginResponse {
  token.Proof proof = 1;
}
