syntax = "proto3";

package webauthn;

import "identity/principal.proto";
import "token/proof.proto";
import "webauthn/authenticator.proto";
import "webauthn/public_key_credential.proto";
import "webauthn/relying_party.proto";

option go_package = "github.com/authaas/api/webauthn";

message AttestationCredential {
  bytes raw_id = 1;
  PublicKeyCredentialType type = 2;
  AuthenticatorAttachment authenticator_attachment = 3;
  bytes client_extension_results = 4;
  AuthenticatorAttestationResponse response = 5;
}

message PublicKeyCredentialCreationOptions {
  bytes challenge = 1;
  uint32 timeout = 2;
  PublicKeyCredentialRpEntity rp = 3;
  identity.Principal user = 4;
  repeated PublicKeyCredentialParameters pub_key_cred_params = 5;
  repeated PublicKeyCredentialDescriptor exclude_credentials = 6;
  AuthenticatorSelectionCriteria authenticator_selection = 7;
  repeated string hints = 8;
  AttestationConveyancePreference attestation = 9;
  repeated string attestation_formats = 10;
  bytes extensions = 11;
}

message BeginRegisterRequest {
  string name = 1;
  string display_name = 2;
}

message BeginRegisterResponse {
  PublicKeyCredentialCreationOptions options = 1;
}

message FinishRegisterRequest {
  AttestationCredential credential = 1;
}

message FinishRegisterResponse {
  token.Proof proof = 1;
}
