// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: services/webauthn.proto

package services

import (
	webauthn "github.com/authaas/api/webauthn"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_services_webauthn_proto protoreflect.FileDescriptor

const file_services_webauthn_proto_rawDesc = "" +
	"\n" +
	"\x17services/webauthn.proto\x12\bservices\x1a\x14webauthn/login.proto\x1a\x17webauthn/register.proto2\xcd\x02\n" +
	"\x0fWebAuthnService\x12P\n" +
	"\rBeginRegister\x12\x1e.webauthn.BeginRegisterRequest\x1a\x1f.webauthn.BeginRegisterResponse\x12S\n" +
	"\x0eFinishRegister\x12\x1f.webauthn.FinishRegisterRequest\x1a .webauthn.FinishRegisterResponse\x12G\n" +
	"\n" +
	"BeginLogin\x12\x1b.webauthn.BeginLoginRequest\x1a\x1c.webauthn.BeginLoginResponse\x12J\n" +
	"\vFinishLogin\x12\x1c.webauthn.FinishLoginRequest\x1a\x1d.webauthn.FinishLoginResponseB!Z\x1fgithub.com/authaas/api/servicesb\x06proto3"

var file_services_webauthn_proto_goTypes = []any{
	(*webauthn.BeginRegisterRequest)(nil),   // 0: webauthn.BeginRegisterRequest
	(*webauthn.FinishRegisterRequest)(nil),  // 1: webauthn.FinishRegisterRequest
	(*webauthn.BeginLoginRequest)(nil),      // 2: webauthn.BeginLoginRequest
	(*webauthn.FinishLoginRequest)(nil),     // 3: webauthn.FinishLoginRequest
	(*webauthn.BeginRegisterResponse)(nil),  // 4: webauthn.BeginRegisterResponse
	(*webauthn.FinishRegisterResponse)(nil), // 5: webauthn.FinishRegisterResponse
	(*webauthn.BeginLoginResponse)(nil),     // 6: webauthn.BeginLoginResponse
	(*webauthn.FinishLoginResponse)(nil),    // 7: webauthn.FinishLoginResponse
}
var file_services_webauthn_proto_depIdxs = []int32{
	0, // 0: services.WebAuthnService.BeginRegister:input_type -> webauthn.BeginRegisterRequest
	1, // 1: services.WebAuthnService.FinishRegister:input_type -> webauthn.FinishRegisterRequest
	2, // 2: services.WebAuthnService.BeginLogin:input_type -> webauthn.BeginLoginRequest
	3, // 3: services.WebAuthnService.FinishLogin:input_type -> webauthn.FinishLoginRequest
	4, // 4: services.WebAuthnService.BeginRegister:output_type -> webauthn.BeginRegisterResponse
	5, // 5: services.WebAuthnService.FinishRegister:output_type -> webauthn.FinishRegisterResponse
	6, // 6: services.WebAuthnService.BeginLogin:output_type -> webauthn.BeginLoginResponse
	7, // 7: services.WebAuthnService.FinishLogin:output_type -> webauthn.FinishLoginResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_webauthn_proto_init() }
func file_services_webauthn_proto_init() {
	if File_services_webauthn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_webauthn_proto_rawDesc), len(file_services_webauthn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_webauthn_proto_goTypes,
		DependencyIndexes: file_services_webauthn_proto_depIdxs,
	}.Build()
	File_services_webauthn_proto = out.File
	file_services_webauthn_proto_goTypes = nil
	file_services_webauthn_proto_depIdxs = nil
}
