syntax = "proto3";

package services;

import "webauthn/login.proto";
import "webauthn/register.proto";

option go_package = "github.com/authaas/api/services";

// WebAuthnService handles WebAuthn/Passkey identity verification
service WebAuthnService {
  // Begin the webauthn registration ceremony
  rpc BeginRegister(webauthn.BeginRegisterRequest) returns (webauthn.BeginRegisterResponse);
  // Finish the webauthn registration ceremony
  rpc FinishRegister(webauthn.FinishRegisterRequest) returns (webauthn.FinishRegisterResponse);

  // Begin the webauthn login ceremony
  rpc BeginLogin(webauthn.BeginLoginRequest) returns (webauthn.BeginLoginResponse);
  // Finish the webauthn login ceremony
  rpc FinishLogin(webauthn.FinishLoginRequest) returns (webauthn.FinishLoginResponse);
}
